# Generated by Django 5.2.3 on 2025-06-22 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_booking_no_of_guests_alter_menu_inventory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='menu',
            new_name='MenuItem',
        ),
    ]
